apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
  # https://github.com/kubernetes-sigs/kustomize/issues/2538
  - https://github.com/argoproj/argo-cd/manifests/cluster-install
  # - github.com/argoproj/argo-rollouts/manifests/cluster-install
resources:
  - argocd-namespace.yaml
patchesStrategicMerge:
  - argocd-cm.yaml
